site_name: MBBank

repo_url: https://github.com/thedtvn/MBBank

nav:
  - Introduction: 'index.md'
  - 'API Documentation':
    - "Sync API": 'api_document/sync_api.md'
    - "Async API": 'api_document/async_api.md'
    - "Image Processing": 'api_document/image_processing.md'

theme:
  name: mkdocs
  color_mode: auto
  user_color_mode_toggle: true
  locale: en

exclude_docs: |
  req.*
  *.py

markdown_extensions:
  - attr_list
  - def_list
  - toc:
      permalink: true